### ISSUE TITLE
Design ideas

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/dicty-components-login#2]
Try out Material-UI. This will be injected in the `head`, then styled-components will be used to override default stylings.

Users should be able to pass in their own styles, which can be opened up using `ThemeProvider`.

Remove "Login" word since it is self explanatory.

**Comment by wildlifehexagon** [comment]
Social login design ideas: https://www.webpagefx.com/blog/web-design/social-logins/

**Comment by cybersiddhu** [comment]
The above has a good list ideas and we could definitely borrow some from there. Few ideas you could implement or explore...

+ Vertical arrangement of the buttons. This is something we have done by default, but keeping it here for completeness.
+ Each button with different background(fill) color which matches the colour of the provider. We do have this, however, i don't think we have the correct colours for each provider.
+ The button needs to stand out from the background and should have a proper size to spacing ratio. It means the size of button and vertical spacing should be responsive.
+ The login page should have a transparent background. It will help the login button to stand out for the user. The header, footer, navbar, link etc could be made a little opaque an should not serve as a  distraction for login.  The login could be a modal component. So, either you could use a contrasting background or modal pattern for login page. If you look through the examples, either of these patterns are used by most of the sites.

**Comment by cybersiddhu** [comment]
Since we are using [material-ui](https://material-ui-next.com), opening the `createMuiTheme` object should be the easiest to change the look and feel of any component. The basic idea would be ...
+ If you have a default `theme` for the default application replace that with the provided `theme` object.
+ If you are using the default setup for default application, have an if else block to pass the provided `theme` object.

Now, MUI could be overridden in couple of ways, Here is an example that uses the `HOC` and `themeprovier` https://material-ui-next.com/customization/themes/#typography
